name: MindTheGapps (17.0.0)

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y zip unzip make

    - name: Clone MindTheGapps repo
      run: |
        git clone --depth=1 --branch cinnamonbun https://gitlab.com/MindTheGapps/vendor_gapps.git
        
    - name: Build MindTheGapps (x86_64)
      run: |
        cd vendor_gapps/
        make gapps_x86_64
        
    - name: Create MTG Release Tag
      run: |
        ZIP_PATH=$(ls vendor_gapps/out/MindTheGapps-*.zip | head -n 1)
        if [ -z "$ZIP_PATH" ]; then
          echo "Build failed: Zip file not found!"
          exit 1
        fi
        ZIP_FILE_NAME=$(basename "$ZIP_PATH" .zip)
        echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV

    - name: Upload MindTheGapps builds to release 🤌
      uses: softprops/action-gh-release@v2
      with:
        files: |
          vendor_gapps/out/MindTheGapps-*.zip
          vendor_gapps/out/MindTheGapps-*.zip.md5sum
        fail_on_unmatched_files: true
        append_body: false
        tag_name: ${{ env.ZIP_FILE_NAME }}
        name: ${{ env.ZIP_FILE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
